<?php

namespace app\models;

use Yii;
use yii\db\Expression;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * @property string $username
 * @property string $email
 * @property string $first_name
 * @property string $last_name
 * @property integer $telephone
 * @property string $password
 * @property string $reset_password_token
 * @property string $email_activation_token
 * @property integer $telephone_activation_token
 * @property string $auth_token
 * @property string $created
 * @property string $modified
 */
class Users extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'email', 'first_name', 'last_name', 'password', 'created', 'modified'], 'required'],
            [['telephone', 'telephone_activation_token'], 'integer'],
            [['telephone', 'username', 'email'], 'unique'],
            [['created', 'modified'], 'safe'],
            [['username', 'email', 'first_name', 'last_name', 'password', 'reset_password_token', 'email_activation_token', 'auth_token'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'email' => 'Email',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'telephone' => 'Telephone',
            'password' => 'Password',
            'reset_password_token' => 'Reset Password Token',
            'email_activation_token' => 'Email Activation Token',
            'telephone_activation_token' => 'Telephone Activation Token',
            'auth_token' => 'Auth Token',
            'created' => 'Created',
            'modified' => 'Modified',
        ];
    }

    public function beforeValidate()
    {
        if ($this->isNewRecord){
            $this->created = new Expression('NOW()');
            $this->modified = new Expression('NOW()');
        }else{
            $this->modified = new Expression('NOW()');
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}
