<?php

namespace app\models;

use Yii;
use yii\db\Expression;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * @property integer $role
 * @property integer $active
 * @property string $username
 * @property string $email
 * @property string $first_name
 * @property string $last_name
 * @property integer $telephone
 * @property string $password
 * @property string $reset_password_token
 * @property string $email_activation_token
 * @property integer $telephone_activation_token
 * @property integer $telephone_activation_session
 * @property string $auth_token
 * @property string $created
 * @property string $modified
 */
class Users extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['role' , 'username', 'email', 'first_name', 'last_name', 'password', 'created', 'modified'], 'required'],
            [['telephone_activation_token','active'], 'integer'],
            [['username', 'email'], 'unique'],
            [['telephone'], 'unique', 'message' => 'Telephone number is already registered.'],
            [['created', 'modified'], 'safe'],
            [['username', 'email', 'first_name', 'last_name', 'password', 'reset_password_token','telephone_activation_session', 'email_activation_token', 'auth_token'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'role' => 'Role',
            'username' => 'Username',
            'email' => 'Email',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'telephone' => 'Telephone',
            'password' => 'Password',
            'reset_password_token' => 'Reset Password Token',
            'email_activation_token' => 'Email Activation Token',
            'telephone_activation_token' => 'Telephone Activation Token',
            'telephone_activation_session' => 'Telephone Activation Session',
            'auth_token' => 'Auth Token',
            'created' => 'Created',
            'modified' => 'Modified',
        ];
    }

    public function beforeValidate()
    {
        if($this->role !== 'user' && $this->role !== 'seller'){
            $this->role = 'user';
        }
        if ($this->isNewRecord){
            $this->created = new Expression('NOW()');
            $this->modified = new Expression('NOW()');
        }else{
            $this->modified = new Expression('NOW()');
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->password = Yii::$app->security->generatePasswordHash($this->password);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function findByUsername($username){
        return self::findByUsername($username);
    }

}
